### PR TITLE
AndroidX and code improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Migrate to AndroidX

### 2nd commit
- Add Java 1.8 support
- Use Java 1.8 features
- (Includes some 5 and 7 migration as well)

### 3rd commit
- Automatic code cleanup by Android Studio

### 4th commit
- Make some inner classes static

### 5th commit
- Fix integer division in floating-point contexts

### 6th commit
- Update the gradle wrapper to 6.1.1 using git bash

### 7th commit
- Even more code cleanup

### CODE REVIEW

**Comment by reloZid** [comment]
Hey! Thanks for your contribution! When trying to start the application it crashes when creating the activity: "You need to use a Theme.AppCompat theme (or descendant) with this activity." I guess the theme files must be migrated as well.

**Comment by TacoTheDank** [comment]
@reloZid Ah, dang.

Maybe I'm just tired, but I've messed around and tried a couple things, and I can't seem to figure out how to fix it. I keep allow edits by maintainers on by default, so if you'd like to take a shot at it, feel free.

**Comment by TacoTheDank** [comment]
Wait, I think I've got it. Gimme a bit to get it together.

**Comment by TacoTheDank** [comment]
@reloZid What I'll probably do is migrate Preferences and that stuff as a separate PR.

**Comment by reloZid** [comment]
Ok. Thanks for having a look at it. In that case I will leave this PR open until the other PR is ready.

**Comment by TacoTheDank** [comment]
@reloZid No no, I didn't want to keep this one staying open because of the Preference stuff, so I decided to remove it from this PR. I think this one is good to merge.

The Preference stuff will be entirely separate.

**Comment by reloZid** [comment]
Oh, sorry I didn't notice that the issue is fixed now. I will merge it then. Thanks!

**Pull request merged**
