### PR TITLE
Removed sound files that were shortcuts

### PR DESCRIPTION
**Pull request by betsythefc**
Added proper sound files

### CODE REVIEW

**Comment by betsythefc** [comment]
This is to correct #42

**Comment by reloZid** [comment]
Thanks a lot!

**Comment by betsythefc** [comment]
No problem! Please confirm you can play them, and if you want me to make any changes to the sounds.

**Comment by reloZid** [comment]
Yes, the files are alright. I'll let you know if I have a working test version.

**Pull request merged**
