### PR TITLE
Auto waves clean

### PR DESCRIPTION
**Pull request by oezgueremir**
Add option to automatically start next wave [as soon as possible]

### CODE REVIEW

**Comment by reloZid** [comment]
Hi, thanks for this pull request! I like the feature but again I think the checkbox is not very intuitive. On my current master I replaced the fast forward checkbox with a toggle button with the label "FF". What do you think about simply turning the "Next Wave" button in such a toggle button instead of the checkbox?

**Comment by reloZid** [comment]
Great, thanks! Yeah, well having them without labels just seems odd to me :-)

**Comment by a-raccoon** [comment]
What does the FF button do exactly? Because it's not automatically sending in the next wave.  And I can't find any instructions explaining the button's purpose.

**Comment by tibisrc** [comment]
it is the fast forward button. you can select the FF speed as powers of 2 up to 32. if you need adjust your weapons and you need more time, you can slow down in the meantime, than speed up again.13.05.2021, 06:40, "a-raccoon" ***@***.***>:
What does the FF button do exactly? Because it's not automatically sending in the next wave.  And I can't find any instructions explaining the button's purpose.

**Comment by reloZid** [comment]
Closed due to inactivity.

**Pull request closed without merging**
