### PR TITLE
Added 3 new levels, and a menu to access them

### PR DESCRIPTION
**Pull request by stephennn**
Hi there,
I created some new levels, and added a menu to access them. Thanks for considering my additions. This is my first pull request on github, so if I am doing something wrong, please just let me know :)

Not sure if I am meant to discuss implementation details here, but a quick rundown of what I changed:
Added a new MenuActivity
 - App now opens to this and allows the user to select a level.
 - When a level is chosen, MainActivity is started with an intent extra that specifies which level to load
 - added some misc graphics and thumbnails for this activity

Added new levels
 - added into res/raw - the levels are clones of the original level except for the platform placement, and path taken by the enemies.

Thanks!

### CODE REVIEW

**Comment by RyDroid** [comment]
Just 1 commit and 1 pull request! It is good to do a branch and a corresponding pull request per idea.
Otherwise, the description of your contribution looks like cool.

**Comment by reloZid** [comment]
Hi @stephennn 

Thanks for your work! Nice logo! I'm currently not sure how I will integrate the levels in the next release, because for me a tower defense has two options:

* Multiple levels with a limited amount of waves and your goal is to master all levels
* One level with unlimited amount of waves and your goal is to survive as long as possible

Multiple levels with unlimited amounts of waves feels more like a sandbox game and is less challenging. Maybe we could combine these two modes (only one level has unlimited waves). This is just my opinion though, maybe there are others?

**Comment by stephennn** [comment]
Haha, no problem. I just threw that image up to have some sort of title there. I tried to keep sketchy-pencil style.

As for levels, I agree with you that the current setup is very much a sandbox mode. For me the most engaging option would be multiple finite levels that you can work your way through, but I see two drawbacks with this. Once you have beat all the levels there is less replay value, and it is likely more work to implement creating _n_ levels instead of one. An endless level can have near endless replay as you keep trying to improve your score, but I found the game became stale after a while playing the same map with the same strategy. That was my main motivation in adding more levels.

If you wish to rework what I have done, or take the project in a different direction, of course by all means go ahead. I will submit a few more PRs here and there, but my contributions will be minor. It would be nice to build out a story mode or something more involved for this game but unfortunately I don't have the time.

**Comment by bellevin** [comment]
Hi guys
Why not keep the focus on the "one level with illimited waves" mode, but give other levels **as bonus** ?
For example, the user can unlock a bonus level when he passes the wave 30, 50, 56, etc for the first time **in the main level**. I mean that these gaps to unlock bonus levels are only present on the main level.
Like this, the game focuses on one level, where the user is pushed to go through as many waves as possible, and the user is rewarded when he achieves to pass difficults waves, and can play on the bonus levels he has unlocked, which means that he will not get bored of the game quickly.

**Pull request merged**
